<?php
//require_once('Utils.inc');

define('GENERAL_SECTION',0);
define('LANG_SECTION', 1);
define('CLASS_SECTION', 2);
define('STILUS_SECTION', 3);
define('PARSER_SECTION', 4);
define('TOPICS_SECTION', 5);
define('SENTIMENT_SECTION', 6);

/*
$data = array(
			GENERAL_SECTION,
			LANG_SECTION=>array("seccion1"=>'<div class="container section">
												<h1> Description</h1>
												<p>	Language Identification is Textalytics' solution to automatic language detection for texts obtained from any kind of source. 
													Through statistic techniques based on N-grams evaluation, more than 60 languages are correctly identified, 
													helping to automatize multilingual sourced applications either by correcting a manual detection preprocessing or by avoiding it altogether.
												</p>
											</div>',
								 "seccion2"=>'',
								 "seccion3"=>'',
								 "seccion4"=>''),
			CLASS_SECTION=>array(),
			STILUS_SECTION=>array(),
			PARSER_SECTION=>array(),
			TOPICS_SECTION=>array(),
			SENTIMENT_SECTION=>array(),
		);
*/
$TITLE = 'Daedalus@GATE';
$DESCRIPTION = '';
$SECTION = '';

?>
