<?php

//Footer.inc
?>

  <!-- Footer -->
  <a name="contacto"></a>
  <div class="footer">
     <div class="offset">
        <h4>Contacto</h4>
        <ul>
          <li><i class="icon-globe"></i> Web: <a href="http://www.daedalus.es">www.daedalus.es</a></li>
          <li><i class="icon-envelope"></i> Correo-E: <a href="mailto:aluna@daedalus.es">aluna@daedalus.es</a></li>
          <li><i class="icon-twitter"></i> Twitter: <a href="https://twitter.com/Daedalus_sa/" target="_blank">@Daedalus_sa</a></li>
        </ul>
      </div>
  </div>

</body>
</html>